require: rubocop-rspec

AllCops:
    NewCops: enable

# Metrics
Metrics/MethodLength:
  Max: 25
Metrics/BlockLength:
  Exclude:
    - config/environments/*
    - lib/tasks/*
    - db/schema.rb
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

# Naming
Naming/MethodParameterName:
  Enabled: false

# Style
Style/Documentation:
  Enabled: false
