require: rubocop-rspec

AllCops:
  NewCops: disable
  Exclude:
    - db/schema.rb

# Metrics
Metrics/MethodLength:
  Max: 25
Metrics/BlockLength:
  Exclude:
    - config/environments/*
    - lib/tasks/*
    - db/schema.rb
    - spec/**/*.rb
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

# Naming
Naming/MethodParameterName:
  Enabled: false

# Style
Style/Documentation:
  Enabled: false
Style/MixinUsage:
  Exclude:
    - spec/factories/users.rb

# Rspec
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
