require: rubocop-rspec

AllCops:
    NewCops: enable

# Metrics
Metrics/MethodLength:
  Max: 15
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

# Style
Style/Documentation:
  Enabled: false
